### ISSUE TITLE
Config misspelling

### ISSUE THREAD

**Issue by lulzmachine** [pinterest/doctorkafka#102]
in https://github.com/pinterest/doctorkafka/blob/b946da94bd7320de74464c82dcf6776e2057ea40/drkafka/config/doctorkafka.properties#L51

The line says
`# [optional] broker replacement interval in seconds
doctorkakka.action.broker_relacement.interval.seconds=43200`

This looks misspelled. Should be "doctorkafka" instead of "doctorkakka"?

**Comment by yuyang08** [comment]
Thanks for reporting the issue! 

Fixed it with https://github.com/pinterest/doctorkafka/commit/ac8b6af69e009b5b51cef225277a4926d9897b70
