### ISSUE TITLE
ec2metadata reference

### ISSUE THREAD

**Issue by fmunteanu** [pinterest/doctorkafka#16]
Hi,

You are making reference to an undocumented dependency:
https://github.com/pinterest/doctorkafka/blob/26779f66639b971cd24e31d4c2b8cb3e5013bd89/kafkastats/src/main/java/com/pinterest/doctorkafka/stats/BrokerStatsRetriever.java#L358

Can you please provide details of the proper `ec2metadata` install to be used with your product?

**Comment by fmunteanu** [comment]
Never mind, you are making reference of the binary `ec2metadata`.

**Comment by venkatwilliams** [comment]
Still see this issue still in the code. How could you fix this dependency?
@yuyang08 @fmunteanu 

BrokerStatsRetriever-
Process process = Runtime.getRuntime().exec("ec2metadata");
Log:
[StatsReporter] ERROR com.pinterest.doctorkafka.stats.BrokerStatsRetriever - Failed to get ec2 metadata
java.io.IOException: Cannot run program "ec2metadata": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_191]
