### ISSUE TITLE
Why need tsdb

### ISSUE THREAD

**Issue by ankitg1989** [pinterest/doctorkafka#2]
Hi Team,
i am trying to use kafkastats before that i have some question .
1. Why we need tsdb ?
2. what is ostrichport ?

**Comment by yuyang08** [comment]
tsdb is used to export metrics for kafkastats process itself in case you have tsdb setup. If you do not have tsdb setup, you can give  some 'localhost:port' parameter to let it go through. 

ostrichport is to specify the port number that you can curl to check kafkastats process metrics. `curl -s localhost:${ostrichport_num}/stats.txt` can expose kafkastats related metrics that can be helpful in diagnosis. 

The following is a command that works on my devhost with dummy tsdhostport setting:

    java  -cp lib/*:kafkastats-0.1.0.jar com.pinterest.doctorkafka.stats.KafkaStatsMain \
         -jmxport 9999 -topic brokerstats -zookeeper zookeeper1/cluster1  \
        -tsdhostport  localhost:12345 -ostrichport 2051  -uptimeinseconds 3600 \
        -pollingintervalinseconds 60 -kafka_config /etc/kafka/server.properties
