### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by allamand** [pinterest/doctorkafka#26]
Hello, does doctorkafka is going to be ported to deal with Kafka clusters deployed on kubernetes ?

**Comment by yuyang08** [comment]
We haven't used doctorkafka with kafka clusters that are deployed on kubernetes yet.  Most likely there are issues that are specific to kubernetes. We welcome contributions from the open source community. 

DoctorKafka's design is orthogonal to the underneath deployment system. KafkaStats should be able to run in the same pod as kafka process. I haven't got time to test that yet.  I am expecting that the partition reassignment part will be the same as non-kubernetes deployment. As for broker replacement, in theory we can supply a script that works with kubernetes deployment to handle the broker replacement in kubernetes environment.  

```doctorkafka.action.broker_replacement.command=$your_script_for_k8s_broker_replacement```
