### ISSUE TITLE
mvn package breaks on OpenJDK

### ISSUE THREAD

**Issue by guilhermef** [pinterest/doctorkafka#3]
Right now, we had to add Openjfx to build on OpenJDK,
mainly because it uses javafx.util.Pair:

https://github.com/pinterest/doctorkafka/blob/6949cc24840a669516aaed173445928f01fc6943/drkafka/src/main/java/com/pinterest/doctorkafka/notification/Email.java#L5
https://github.com/pinterest/doctorkafka/blob/6949cc24840a669516aaed173445928f01fc6943/kafkastats/src/main/java/com/pinterest/doctorkafka/util/OperatorUtil.java#L7
https://github.com/pinterest/doctorkafka/blob/6949cc24840a669516aaed173445928f01fc6943/drkafka/src/main/java/com/pinterest/doctorkafka/KafkaClusterManager.java#L15

It would be ok to replace javafx.util.Pair with another structure ?
Thanks.

**Comment by yuyang08** [comment]
This issue has been fixed Guilherme's change: https://github.com/pinterest/doctorkafka/pull/4
