### ISSUE TITLE
build for kafka 0.9.0.1 failed

### ISSUE THREAD

**Issue by modeyang** [pinterest/doctorkafka#5]
when build for 0.9.0.1, change pom.xml and build it ; changed content below
```
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.10</artifactId>                                                                                                                                                                                     
            <version>0.9.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>0.9.0.1</version>
        </dependency>

```
compile failed with 
``` [ERROR] /root/git_workspace/doctorkafka/kafkastats/src/main/java/com/pinterest/doctorkafka/util/OperatorUtil.java:[18,38] error: cannot find symbol```

then refer code
```
 18 import org.apache.kafka.common.network.ListenerName;                                                                                                                                                                            
 19 import org.apache.kafka.common.protocol.SecurityProtocol;
```

can not Compatible with kafka of backward version?  any help with appreciate

**Comment by yuyang08** [comment]
you will need to update doctorkafka code for kafka 0.9.x , as there has been changes in SecurityProtocol related packages in doctorkafka.  currently we have been using kafka 0.10.x or newer versions in production, resolving this as won't fix.
