### ISSUE TITLE
Release Cycle

### ISSUE THREAD

**Issue by Sniedes722** [pinterest/doctorkafka#66]
Just want to say up front this project looks awesome! Totally caught my eye for a few reasons, as dealing with failed brokers & topic under-replication are, in my opinion, two of the biggest pain points of cluster management/maintenance (plus the UI is sweet). However, I noticed there haven't been any releases yet, and I would be a bit hesitant to put it on a production cluster given such. Are there are plans for an official release? Would really love to use `doctorkafka` and contribute back, thank you very much.

**Comment by yuyang08** [comment]
We release DoctorKafka 0.2.4.3 today.  Let us know if you see any problem with it. 

https://github.com/pinterest/doctorkafka/tree/0.2.4.3
